### ISSUE TITLE
Exception thrown when ignored file or directory does not exist

### ISSUE THREAD

**Issue by acodeninja** [acodeninja/continuous-security#65]
## What?

```yaml
ignore:
  - random/directory/
scanners:
  - "@continuous-security/scanner-test"
```

If the directory `random/directory/` does not exist an exception is raised:

```
[scan:started] 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, lstat '/tmp/project-EkbBrs/build'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/tmp/project-EkbBrs/build'
}
```
